// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```ac
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb_i9OaLxyaNz_Ob9J7ZCkz6U1PvHCJsc',
    appId: '1:118807070131:web:3f91dd154aa8546aebb7c6',
    messagingSenderId: '118807070131',
    projectId: 'queueless-queue',
    authDomain: 'queueless-queue.firebaseapp.com',
    storageBucket: 'queueless-queue.firebasestorage.app',
    measurementId: 'G-Q0BWRWNN4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCgqudRvPwmlazdpWsZC2DO51qZgXDp4w',
    appId: '1:118807070131:android:62a9f84079f972a3ebb7c6',
    messagingSenderId: '118807070131',
    projectId: 'queueless-queue',
    storageBucket: 'queueless-queue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV2_mxHpG4YU2KiyL7Q9YeVgkMrOQOphg',
    appId: '1:118807070131:ios:d30f8d5063284ed5ebb7c6',
    messagingSenderId: '118807070131',
    projectId: 'queueless-queue',
    storageBucket: 'queueless-queue.firebasestorage.app',
    iosBundleId: 'com.example.queuelessQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV2_mxHpG4YU2KiyL7Q9YeVgkMrOQOphg',
    appId: '1:118807070131:ios:d30f8d5063284ed5ebb7c6',
    messagingSenderId: '118807070131',
    projectId: 'queueless-queue',
    storageBucket: 'queueless-queue.firebasestorage.app',
    iosBundleId: 'com.example.queuelessQueue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb_i9OaLxyaNz_Ob9J7ZCkz6U1PvHCJsc',
    appId: '1:118807070131:web:5ce60117752121e7ebb7c6',
    messagingSenderId: '118807070131',
    projectId: 'queueless-queue',
    authDomain: 'queueless-queue.firebaseapp.com',
    storageBucket: 'queueless-queue.firebasestorage.app',
    measurementId: 'G-J1CBS8716Q',
  );
}
